#!/bin/bash
#
# Verification Proof Checklist
# ============================
# Prints canonical proof requirements for CI verification.
# This script is network-free and produces plain text only.
#
# Usage: bash scripts/gha_proof_checklist.sh
#

# No ANSI codes, no symbols, no emojis - plain text only

echo ""
echo "========================================================================"
echo "VERIFICATION PROOF CHECKLIST"
echo "========================================================================"
echo ""
echo "This checklist defines the canonical proof signals for verification."
echo "Proof is valid regardless of trigger mechanism (push, PR, dispatch)."
echo ""

echo "------------------------------------------------------------------------"
echo "SECTION 1: CANONICAL PROOF STRINGS"
echo "------------------------------------------------------------------------"
echo ""
echo "The following strings MUST appear in the CI logs for proof to be valid."
echo ""
echo "  String 1 (must appear EXACTLY ONCE):"
echo "    SYNC-02: admin_sync_returns_full_contract"
echo ""
echo "  String 2 (must appear AT LEAST ONCE):"
echo "    MARKER GATE PASSED: tenant="
echo ""
echo "Search for these exact strings in the workflow logs."
echo "Count occurrences of String 1 - it must be exactly 1."
echo ""

echo "------------------------------------------------------------------------"
echo "SECTION 2: CANONICAL ARTIFACTS"
echo "------------------------------------------------------------------------"
echo ""
echo "The following artifacts MUST be present in the CI run."
echo ""
echo "  Artifact 1: sync-contract-marker"
echo "    Contains: Marker JSON file (/tmp/carfax_sync02_ok.marker)"
echo ""
echo "  Artifact 2: carfax-reports"
echo "    Contains: CARFAX test report JSON files"
echo ""
echo "Verify both artifacts appear in the workflow run's artifact section."
echo ""

echo "------------------------------------------------------------------------"
echo "SECTION 3: PROOF VALIDITY CRITERIA"
echo "------------------------------------------------------------------------"
echo ""
echo "A verification run constitutes valid proof if and only if:"
echo ""
echo "  [ ] Workflow completed successfully (not failed/cancelled)"
echo "  [ ] SYNC-02 string appears exactly once"
echo "  [ ] MARKER GATE PASSED string appears at least once"
echo "  [ ] Artifact sync-contract-marker is present"
echo "  [ ] Artifact carfax-reports is present"
echo ""

echo "------------------------------------------------------------------------"
echo "SECTION 4: EVIDENCE TEMPLATE"
echo "------------------------------------------------------------------------"
echo ""
echo "Copy and complete this template:"
echo ""
echo "  VERIFICATION EVIDENCE"
echo "  ====================="
echo ""
echo "  Workflow Run URL:"
echo "    [paste URL]"
echo ""
echo "  SYNC-02 Log Line:"
echo "    [paste line containing: SYNC-02: admin_sync_returns_full_contract]"
echo ""
echo "  Marker Gate Log Line:"
echo "    [paste line containing: MARKER GATE PASSED: tenant=]"
echo ""
echo "  SYNC-02 Count: [1]"
echo ""
echo "  Artifacts Present:"
echo "    sync-contract-marker: [YES/NO]"
echo "    carfax-reports: [YES/NO]"
echo ""
echo "  Verification Status: [PASS/FAIL]"
echo ""

echo "------------------------------------------------------------------------"
echo "SECTION 5: REPOSITORY AUDIT"
echo "------------------------------------------------------------------------"
echo ""
echo "Before declaring proof complete, audit for hardcoded paths:"
echo ""
echo "  Command:"
echo "    grep -rn '\"/app' *.sh docs/*.md scripts/*.sh 2>/dev/null | grep -v '#'"
echo ""
echo "  Expected: No matches (or only fallback paths in deprecated code)"
echo ""

echo "------------------------------------------------------------------------"
echo "SECTION 6: NON-PROOF RUNS"
echo "------------------------------------------------------------------------"
echo ""
echo "Some workflows intentionally exclude sync calls (e.g., PR checks)."
echo "These runs are valid but do NOT establish sync-contract proof."
echo ""
echo "To verify a non-proof run is correctly configured:"
echo "  [ ] Workflow completes successfully"
echo "  [ ] SYNC-02 string does NOT appear"
echo "  [ ] No marker artifacts uploaded"
echo ""

echo "========================================================================"
echo "END OF CHECKLIST"
echo "========================================================================"
echo ""
echo "Reference: docs/github_actions_proof_runbook.md"
echo ""
